# Generated by Django 3.2.22 on 2023-11-21 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='../https://res.cloudinary.com/db6t1xmmn/image/upload/v1697453100/samples/ecommerce/analog-classic.jpg', upload_to='images/'),
        ),
    ]
